name: ashish_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  visibility_detector: ^0.4.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ashish_fhd.png
    - assets/iPhone 13 Pro.png
    - assets/Sign Up.png
    - assets/stock_app_image.png
    - assets/Pemaxx.png
    - assets/u.png
    - assets/sarvo.png
    - assets/urban.jpeg
    - assets/ezt.jpeg
    - assets/mobitel.jpeg
    - assets/track.png
    - assets/pemx.png
    - assets/pemax.png
    - assets/ezymart.jpeg
    - assets/ezym.jpeg
    - assets/food.jpeg
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/service.jpeg
    - assets/service1.jpeg
    - assets/service2.jpeg  
    - assets/mart.jpeg
    - assets/mart2.jpeg
    - assets/mart1.jpeg








 